export enum siteRoutes {
  login = "/auth/login",
  home = "/",
  dashboard = "/dashboard",
  projects = "/projects",
  projectsCreate = "/projects/create",
  projectsView = "/projects/view/:id",
  projectsEdit = "/projects/edit/:id",
  activity = "/activity",
  activityCreate = "/activity/create",
  activityEdit = "/activity/edit/:id",
  vendors = "/vendors",
  vendorsCreate = "/vendors/create",
  vendorsView = "/vendors/view/:id",
  vendorsEdit = "/vendors/edit/:id",
  cashflow = "/cashflow",
  prospects = "/prospects",
  prospectsCreate = "/prospects/create",
  prospectsView = "/prospects/view/:id",
  prospectsEdit = "/prospects/edit/:id",
  reportsProjectList = "/reports/project-list",
  reportsVendorList = "/reports/vendor-list",
  profile = "/profile",
}
